export const classList = [
  {
    id: "math-10",
    title: "Mathematics",
    code: "MATH101",
    teacher: "Ms Nguyen Thi Lan",
    schedule: "Mon, Thu - 07:00",
    progress: 72,
    completedLessons: 18,
    totalLessons: 25,
    assignmentsPending: 2,
    className: "Grade 10",
    room: "A-203",
    description:
      "Focuses on algebra, functions, and step-by-step problem-solving skills.",
    nextClass: "Thu, 07:00 - 08:30",
    attendance: 96,
    teacherEmail: "lan.nguyen@school.edu.vn",
    assignments: [
      { id: "m1", title: "Function Chapter Worksheet", due: "12/03/2026", status: "In Progress" },
      { id: "m2", title: "Midterm Practice Set", due: "19/03/2026", status: "Not Started" },
    ],
    lessons: [
      { id: "ml1", title: "Linear Functions", time: "Mon - 07:00" },
      { id: "ml2", title: "Function Graphs", time: "Thu - 07:00" },
      { id: "ml3", title: "Comprehensive Practice", time: "Mon - 07:00" },
    ],
    resources: ["Week 8 Lecture Slides", "Practice Test Set 01", "Quick Formula Sheet"],
  },
  {
    id: "eng-11",
    title: "English",
    code: "ENG201",
    teacher: "Mr Tran Minh Duc",
    schedule: "Tue, Fri - 13:30",
    progress: 84,
    completedLessons: 21,
    totalLessons: 25,
    assignmentsPending: 1,
    className: "Grade 11",
    room: "B-105",
    description:
      "Develops listening, speaking, reading, and writing skills by term topics.",
    nextClass: "Fri, 13:30 - 15:00",
    attendance: 98,
    teacherEmail: "duc.tran@school.edu.vn",
    assignments: [
      { id: "e1", title: "Unit 6 Quiz", due: "14/03/2026", status: "In Progress" },
      { id: "e2", title: "Essay: Future Jobs", due: "22/03/2026", status: "Not Started" },
    ],
    lessons: [
      { id: "el1", title: "Grammar: Relative Clauses", time: "Tue - 13:30" },
      { id: "el2", title: "Speaking Workshop", time: "Fri - 13:30" },
      { id: "el3", title: "Reading Practice", time: "Tue - 13:30" },
    ],
    resources: ["Unit 6 Vocabulary List", "Pronunciation Practice", "Writing Template"],
  },
  {
    id: "phy-12",
    title: "Physics",
    code: "PHY301",
    teacher: "Ms Pham Thu Ha",
    schedule: "Wed - 09:00",
    progress: 66,
    completedLessons: 16,
    totalLessons: 24,
    assignmentsPending: 3,
    className: "Grade 12",
    room: "Lab-01",
    description:
      "Learning through applications, experiments, and real-life physics analysis.",
    nextClass: "Wed, 09:00 - 10:30",
    attendance: 93,
    teacherEmail: "ha.pham@school.edu.vn",
    assignments: [
      { id: "p1", title: "Experiment Report", due: "16/03/2026", status: "In Progress" },
      { id: "p2", title: "Electric Current Exercises", due: "20/03/2026", status: "Not Started" },
      { id: "p3", title: "Chapter 5 Review", due: "25/03/2026", status: "Not Started" },
    ],
    lessons: [
      { id: "pl1", title: "Direct Current", time: "Wed - 09:00" },
      { id: "pl2", title: "Mixed Circuits", time: "Wed - 09:00" },
      { id: "pl3", title: "Comprehensive Exercises", time: "Wed - 09:00" },
    ],
    resources: ["Lab Handbook", "Simulation Videos", "Multiple-choice Question Bank"],
  },
];

export const upcomingTasks = [
  { id: 1, title: "Submit Function Chapter Worksheet", subject: "Mathematics", due: "12/03/2026" },
  { id: 2, title: "Unit 6 Quiz", subject: "English", due: "14/03/2026" },
  { id: 3, title: "Submit Experiment Report", subject: "Physics", due: "16/03/2026" },
];
