export { default as AdminDashboard } from "./dashboard/AdminDashboard";
export { default as AdminUsers } from "./users/AdminUsers";
export { default as AdminQuiz } from "./quiz/AdminQuiz";
export { default as AdminCreateQuiz } from "./quiz/create/AdminCreateQuiz";
export { default as AdminClasses } from "./classes/AdminClasses";
export { default as AdminPayment } from "./payment/AdminPayment";
export { default as AdminTimetable } from "./timetable/AdminTimetable";
export { default as AdminReports } from "./reports/AdminReports";
export { default as AdminNotifications } from "./notifications/AdminNotifications";
